package com.fastwork.toefl.utils

const val DATABASE_NAME = "toefl-db"
const val PARAGRAPH_FILE_DATA_NAME = "paragraph.json"
const val READING_FILE_DATA_NAME = "reading.json"
const val STRUCTURE_FILE_DATA_NAME = "structure.json"
const val LISTENING_FILE_DATA_NAME = "listening.json"
const val USER_FILE_DATA_NAME = "user.json"
const val TEST_TYPE_KEY = "test_type"
const val SCORE_TYPE_KEY = "score_type"
const val USER_ID_KEY = "user_id"
const val PRE_TEST_CHANCE_KEY = "pre_test_chance"
const val POST_TEST_CHANCE_KEY = "post_test_chance"
const val DIRECTION_KEY = "direction_key"
const val SESSION_KEY = "session_key"
const val TEST_CATEGORY_KEY = "test_category"
const val SCORE_CATEGORY_KEY = "score_category"